### PR TITLE
.NET Standard port

### LINKED ISSUE #118: .NET Core support
Currently the full .NET framework is required to use this client SDK.  Could plans be made to provide a .NET Core build for newer / cross-platform projects?

### PR DESCRIPTION
**Pull request by DavidRouyer**
- [x] The library now have two targets : .NET Framework 4.5.2 (net452) and .NET Standard 2.0 (netstandard2.0)
- [x] Dependency cleanup (libraries updated to target both frameworks)
- [x] New project structure (documentation in _docs_, source project in _src_, test projects in _tests_)
- [x] Travis now run the full test suite on Mono and .NET Core and both Debug and Release configuration

Mono tests are allowed to fail due to: https://bugzilla.xamarin.com/show_bug.cgi?id=59221

fixes #118

### CODE REVIEW

**Comment by DavidRouyer** [comment]
Can someone take a look? cc @Ergin008 @InbarGazit @mmallis87

**Comment by moraleslos** [comment]
Ok I'm using your @DavidRouyer code and compilation is all good however when running I get the following error: 

> ":"Could not load type 'System.IdentityModel.Tokens.JwtSecurityTokenHandler' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'."}

Looks like you'll need to drop to version 4.0 based on this issue:  [https://github.com/aspnet/AspNetKatana/issues/76](url)

If you can drop that version to 4.0, I think it should work.  Let me know as well so I can grab your latest and test it out.

**Comment by DavidRouyer** [comment]
Are you sure you don't have mixed versions of the dependency as stated [here](https://github.com/aspnet/AspNetKatana/issues/76#issuecomment-352554182)?

**Comment by moraleslos** [comment]
@DavidRouyer I'm fairly certain, although I'm running into other issues at the moment.  Does your current branch work / tested with the call to apiClient.ConfigureJwtAuthorizationFlow()?  This is where it fails for me  using your original code.

**Comment by DavidRouyer** [comment]
@moraleslos Are you using .NET Core or the full framework?
ConfigureJwtAuthorizationFlow() is tested [here](https://github.com/DavidRouyer/docusign-csharp-client/blob/master/tests/DocuSign.eSign.Test/Auth/JwtAuthUnitTests.cs#L21)

**Comment by moraleslos** [comment]
@DavidRouyer .NET Core 2.0:

  ```
<PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.1" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
  </ItemGroup>
```

**Comment by DavidRouyer** [comment]
@moraleslos What version of the .NET Core SDK are you using? You can type ` dotnet --version`

**Comment by moraleslos** [comment]
@DavidRouyer 2.1.2

**Comment by DavidRouyer** [comment]
@moraleslos I have the same version, have you tried to run the tests? They should work. I'll investigate when I have time

**Comment by moraleslos** [comment]
@DavidRouyer I actually just nuget your code into a local repo and added it to one of my projects  ;-)  I will test it out-- both just your solution and then integrated into my solution.  I'll keep you posted.

**Comment by DavidRouyer** [comment]
@moraleslos Are you using System.IdentityModel.Tokens.Jwt or is it linked by another dependency in your solution? Or is it a new project? If you're trying to use it in a existing project it can be a mixed version dependency error (check all of your dependencies), if not you can create a minimum reproducible example project on GitHub and pass it to me, it can save me some time :)

**Comment by moraleslos** [comment]
@DavidRouyer ok your tests pass.  must be something with my current project.  I'll look into it and follow up with you.  thanks!

**Comment by samarth202** [comment]
Any update on this ?

**Comment by aaronpowell** [comment]
Is there an ETA on what it'd take to get this through to merged? We're building an ASP.NET Core 2.0 app and wanting to use DocuSign in it. Happy to build locally if you want a test to see if it can be integrated, but long-term I would much prefer to pull it from NuGet.

**Comment by DavidRouyer** [comment]
Is there any maintainer who can take a look at this? It is there since the end of november.

**Comment by gswartz777** [comment]
I've cloned your branch and though it builds I get 8 failing tests.  Two of them are the OAuthResourceOwnerPasswordGrantTest - Not implemented.  But the other 6 are the Jwt and Legacy CreateEmbeddedConsoleViewTest, CreateEmbeddedSendingViewTest and CreateEmbeddedSigningViewTest tests.  

They all fail with the error - The system cannot find the file specified pointing to the line where it calls System.Diagnostics.Process.Start(viewUrl.Url);  Do I need to reference something beyond what's included in the branch?

**Comment by DavidRouyer** [comment]
Some of them are integration tests (I tagged them with [Category("Manual")]) and they should launch your default browser. A few of them requires authentication, if you see a login page in the launched browser you need to log in.

**Comment by gswartz777** [comment]
After referencing the branch in my .net core mvc app I get to the point of calling the apiclient Login and get the error DocuSign.eSign.Client.ApiException: 'Error calling Login: Operation is not supported on this platform.'

`LoginInformation loginInfo = authApi.Login();`

This is after successfully getting the access token from the apiclient GetOAuthToken method.  Any idea why?

**Comment by DavidRouyer** [comment]
Which version of .NET Core are you using? Try the legacy authentication

**Comment by gswartz777** [comment]
I'm using .net core 2.  Sorry I'm still trying to figure all of this out.  What is the legacy authentication?

**Comment by DavidRouyer** [comment]
In the [Readme](https://github.com/docusign/docusign-csharp-client/blob/master/README.md), take a look at the part 'To send a signature request from a template using legacy authentication'
The error 'Operation is not supported on this platform.' comes from [RestSharp](https://github.com/restsharp/RestSharp/search?q=Operation+is+not+supported&type=Issues) (probably when you use OAuth)

**Comment by gswartz777** [comment]
Thanks.  Gave that a try and still get the same error.  I feel like giving up on the sdk and just using webclient requests for all of this stuff.  I have half of what I need working with that at this point.

**Comment by DavidRouyer** [comment]
Try to rollback to RestSharp 106.1.0, but it should work

**Comment by RajRele** [comment]
Thanks @DavidRouyer for your attempt on the .Net Standard... We have published a pre-release version of the .Net Standard 2.0. Please try and let us know what you think. 
https://github.com/docusign/docusign-csharp-client
https://www.nuget.org/packages/DocuSign.eSign.dll/3.0.0-rc

Regards

**Pull request closed without merging**
