### PR TITLE
DocuSign API should only use TLS 1.1 and TLS 1.2 #178

### PR DESCRIPTION
**Pull request by FJBDev**

### CODE REVIEW

**Comment by RajRele** [comment]
@FJBDev thanks for PR, we do not want to upgrade our base library to 4.7 as we want to keep supporting existing implementation. We did something similar on setting up the TLS to 1.2.

**Comment by FJBDev** [comment]
@RajRele : Sure, i understand why you want to keep .NET 4.5. However, be aware that while you mention "vWe did something similar on setting up the TLS to 1.2.", it is not similar. The current code will need to be re-written when TLS 1.3 is out as the code only specify TLS 1.1 and Tls 1.2.
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;

The difference I am bringing with my PR is the fact that no further code change will be needed as I only make sure to exclude SSL3 and TLS1.0
// SSL 3.0 and TLS 1.0 have to be turned off
protocolVersions &= ~SecurityProtocolType.Ssl3;
protocolVersions &= ~SecurityProtocolType.Tls

**Comment by RajRele** [comment]
@FJBDev you are right. Your point is noted and much appreciated. I will try to push this to swagger and future releases. Thanks again.

**Comment by FJBDev** [comment]
@RajRele Thanks, I have updated my pull requests and removed the upgrade to .NET 4.7

**Comment by RajRele** [comment]
@FJBDev thanks for your contribution, we have created a pre-release version and added your contribution to our SDK. 
https://github.com/docusign/docusign-csharp-client/blob/master/CHANGELOG.md
Thanks again...

**Comment by FJBDev** [comment]
@RajRele Thanks for the update!

**Comment by RajRele** [comment]
Closing this PR! changes [here](https://jira.corp.docusign.com/browse/DCM-2748).

**Pull request closed without merging**
