### PR TITLE
Fixed the scaleValue data type

### PR DESCRIPTION
**Pull request by mmallis87**

### CODE REVIEW

**Comment by imranmp** [comment]
Is this bug fix not included in the latest Nuget package (2.1.5)? I am getting the error for it when calling the ListRecipients on EnvelopesApi

Error converting value 1 to type 'DocuSign.eSign.Model.Number'. Path 'signers[0].tabs.signHereTabs[0].scaleValue'

**Comment by imranmp** [comment]
There is also a bug in the latest Nuget package (2.1.5) when calling EnvelopesApi.CreateTabs. 

--> DocuSign.eSign.Client.ApiException Error converting value 0 to type 'DocuSign.eSign.Model.Number'. Path 'signHereTabs[0].scaleValue', line 4, position 23. System.Object Deserialize(RestSharp.IRestResponse, System.Type)    at DocuSign.eSign.Client.ApiClient.Deserialize(IRestResponse response, Type type)
   at DocuSign.eSign.Api.EnvelopesApi.CreateTabsWithHttpInfo(String accountId, String envelopeId, String recipientId, Tabs tabs)
   at DocuSign.eSign.Api.EnvelopesApi.CreateTabs(String accountId, String envelopeId, String recipientId, Tabs tabs)

**Comment by colson22** [comment]
This issue is resolved in the source, but not yet available in the NuGet
package.  If you build from source,  you should be good to go.

Hopefully they will refresh the NuGet package soon.

Frank


Bfrank Colson
colson22@gmail.com
Please consider the environment before printing this email.

**Comment by codingdawg** [comment]
Here is the internal DocuSign bug tracking Id. DCM-1739. We are working on this.

**Pull request merged**
