### PR TITLE
Fix for RestSharp Dependency Issue #101

### PR DESCRIPTION
**Pull request by brprigge**
Upgraded RestSharp Dependency and tested locally.

### CODE REVIEW

**Comment by RajRele** [comment]
@brprigge thank you for your contribution, at this point we don't directly merge PRs. We will have to research on the breaking changes RestSharp has created due to these versions, will put this in our roadmap.

**Comment by brprigge** [comment]
> @brprigge thank you for your contribution, at this point we don't directly merge PRs. We will have to research on the breaking changes RestSharp has created due to these versions, will put this in our roadmap.

What is the timeline on the roadmap?  This is preventing us from using your service currently.

**Comment by RajRele** [comment]
Sorry you facing these challenges. Just curious are you using .net core or .net framework?

I see this has already been added to our roadmap will be out with our next release cycle, which will be somewhere in first two weeks of June.

**Comment by RajRele** [comment]
We have a pre-release published on Nuget.  
https://www.nuget.org/packages/DocuSign.eSign.dll/4.5.0-rc

**Pull request closed without merging**
